# 使用稳定的官方Python镜像
FROM python:3.10-alpine

# 安装必需的依赖
RUN pip install --no-cache-dir yq

# 将评测脚本复制到镜像中
COPY run.sh /usr/local/bin/run.sh

# 授予脚本执行权限
RUN chmod +x /usr/local/bin/run.sh

# 将 run.sh 设置为容器的主可执行文件
ENTRYPOINT ["/usr/local/bin/run.sh"]

# 默认参数为空，用户可在 docker run 时传入
CMD []
