server:
  port: 9999

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG
    org.mybatis: DEBUG
    com.OMS.user_service.client: DEBUG

spring:
  ai:
    openai:
      api-key: sk-2feb773ffa724ed091202a36dabf4ee6
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat

