server:
  port: 7777

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:5555
          predicates:
            - Path=/user/**
        - id: contest
          uri: http://contest:1234
          predicates:
            - Path=/contest/**
        - id: practice
          uri: http://practice:2222
          predicates:
            - Path=/practice/**

auth:
  service:
    url: http://user:5555
    on: false


