server:
  port: 7777

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:5555
          predicates:
            - Path=/user/**
        - id: practice
          uri: http://practice:2222
          predicates:
            - Path=/practice/**
        - id: contest
          uri: http://contest:1234
          predicates:
            - Path=/contest/**
        - id: sys
          uri: http://sys:2121
          predicates:
            - Path=/sys/**
        - id: advice
          uri: http://advice:9999
          predicates:
            - Path=/advice/**
      #跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods: "*"
            allowedHeaders: "*"
            allowedOriginPatterns: "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG

auth:
  service:
    url: http://user:5555
    on: false


