server:
  port: 9999

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG
    org.mybatis: DEBUG
    com.OMS.user_service.client: DEBUG

spring:
  ai:
    openai:
      api-key: sk-fb685d433790407d9154ae7101c7ace5
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat

