
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    mem_limit: 256m
    mem_reservation: 128m

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9005:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: LETUC0J123
    volumes:
      - ../minio/data:/data
    command: server /data --console-address ":9001"
    mem_limit: 1g
    mem_reservation: 512m

  practice:
    image: practice:latest
    container_name: practice
    ports:
      - "2222:2222"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  gateway:
    image: gateway:latest
    container_name: gateway
    ports:
      - "7777:7777"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  contest:
    image: contest:latest
    container_name: contest
    ports:
      - "1234:1234"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      
  sys:
    image: sys:latest
    container_name: sys
    ports:
      - "2121:2121"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      # ↓↓↓ 新增一行，覆盖 application.yml 中的 mysql.host
      - MYSQL_HOST=mysql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: "0:0"

  user:
    image: user:latest
    container_name: user
    ports:
      - "5555:5555"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  # run:
  #   image: run:latest
  #   container_name: run
  #   ports:
  #     - "1001:1001"
  #   restart: on-failure
  #   mem_limit: 512m
  #   mem_reservation: 256m
  #   environment:
  #     - JAVA_OPTS=-Xms256m -Xmx512m

  advice:
    image: advice:latest
    container_name: advice
    ports:
      - "9999:9999"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/letucoj.sql:/docker-entrypoint-initdb.d/letucoj.sql
      - ../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: '430103535'
      MYSQL_DATABASE: letucoj
    mem_limit: 2g
    mem_reservation: 1g

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ../es/data:/usr/share/elasticsearch/data
      - ../es/elasticsearch-analysis-ik-7.16.1.zip:/tmp/ik.zip:ro
    mem_limit: 2g
    mem_reservation: 1g
    entrypoint: >
      /bin/bash -c '
        if [ ! -d /usr/share/elasticsearch/plugins/ik ]; then
          bin/elasticsearch-plugin install --batch file:///tmp/ik.zip;
        fi &&
        exec /usr/local/bin/docker-entrypoint.sh
      '


volumes:
  elasticsearch-data:
    external: true