version: "3.8"
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    mem_limit: 256m
    mem_reservation: 128m

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9005:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: LETUC0J123
    volumes:
      - ../minio/data:/data
    command: server /data --console-address ":9001"
    mem_limit: 1g
    mem_reservation: 512m

  practice:
    image: practice:latest
    container_name: practice
    ports:
      - "2222:2222"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  gateway:
    image: gateway:latest
    container_name: gateway
    ports:
      - "7777:7777"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  contest:
    image: contest:latest
    container_name: contest
    ports:
      - "1234:1234"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      
  sys:
    image: sys:latest
    container_name: sys
    ports:
      - "2121:2121"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: "0:0"
    privileged: true


  user:
    image: user:latest
    container_name: user
    ports:
      - "5555:5555"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run:
    image: run:latest
    container_name: run
    ports:
      - "1001:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  advice:
    image: advice:latest
    container_name: advice
    ports:
      - "9999:9999"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/letucoj.sql:/docker-entrypoint-initdb.d/letucoj.sql
      - ../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: '430103535'
      MYSQL_DATABASE: letucoj
    mem_limit: 2g
    mem_reservation: 1g

  run0:
    image: run:latest
    container_name: run0
    ports:
      - "1010:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run1:
    image: run:latest
    container_name: run1
    ports:
      - "1011:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run2:
    image: run:latest
    container_name: run2
    ports:
      - "1012:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run3:
    image: run:latest
    container_name: run3
    ports:
      - "1013:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run4:
    image: run:latest
    container_name: run4
    ports:
      - "1014:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run5:
    image: run:latest
    container_name: run5
    ports:
      - "1015:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run6:
    image: run:latest
    container_name: run6
    ports:
      - "1016:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run7:
    image: run:latest
    container_name: run7
    ports:
      - "1017:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run8:
    image: run:latest
    container_name: run8
    ports:
      - "1018:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run9:
    image: run:latest
    container_name: run9
    ports:
      - "1019:1001"
    restart: on-failure
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
