services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    mem_limit: 256m
    mem_reservation: 128m

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9005:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: LETUC0J123
    volumes:
      - ../minio/data:/data
    command: server /data --console-address ":9001"
    mem_limit: 1g
    mem_reservation: 512m

  practice:
    image: practice:latest
    container_name: practice
    ports:
      - "2222:2222"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  gateway:
    image: gateway:latest
    container_name: gateway
    ports:
      - "7777:7777"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  contest:
    image: contest:latest
    container_name: contest
    ports:
      - "1234:1234"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  sys:
    image: sys:latest
    container_name: sys
    ports:
      - "2121:2121"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - MYSQL_HOST=mysql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: "0:0"

  user:
    image: user:latest
    container_name: user
    ports:
      - "5555:5555"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  run:
    image: run:latest
    container_name: run
    ports:
      - "1001:1001"
    restart: on-failure
    privileged: true
    cgroup: host
    volumes:
      - ./user:/app/user
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - HOST_DIR=${HOST_DIR}

  advice:
    image: advice:latest
    container_name: advice
    ports:
      - "9999:9999"
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/letucoj.sql:/docker-entrypoint-initdb.d/letucoj.sql
      - ../mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: '430103535'
      MYSQL_DATABASE: letucoj
    mem_limit: 2g
    mem_reservation: 1g

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - gateway
    mem_limit: 128m
    mem_reservation: 64m

volumes:
  toolchain:
