# -------------- 基础：官方已瘦身 JRE --------------
FROM openjdk:17-slim

# 安装 docker-cli
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        docker.io; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
            /usr/share/doc/* /usr/share/man/* /usr/share/info/*

WORKDIR /app

RUN mkdir -p user

COPY run.jar /app/
RUN chmod +x /app/run.jar

ENV JAVA_OPTS="-Xms256m -Xmx512m -XX:+UseContainerSupport"
EXPOSE 1001
CMD ["sh", "-c", "exec java $JAVA_OPTS -jar /app/run.jar"]