spring:
  application:
    name: practice
  data:
    redis:
      host: redis
      port: 6379
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

mq:
  type: rocketmq

rocketmq:
  name-server: rocketmq-namesrv:9876
  producer:
    group: my-producer-group
  consumer:
    group: my-consumer-group

#logging:
#  level:
#    root: INFO
#    org.springframework: DEBUG
#    com.zaxxer.hikari: DEBUG
#    org.mybatis: DEBUG
#    com.OMS.practice_service: DEBUG

