apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-spring-app
spec:
  containers:
    - name: my-container
      image: run1.0:run
      ports:
        - containerPort: 1111
          hostPort: 1112
