# 使用官方 Node.js 18 镜像作为基础
FROM node:18

# 将前面编写的脚本复制到镜像中
COPY run.sh /usr/local/bin/run.sh

# 授予脚本执行权限
RUN chmod +x /usr/local/bin/run.sh

# 将 run-js.sh 设置为容器的主可执行文件
# 当您使用 `docker run` 并传入参数时，这些参数会作为 run-js.sh 的输入
ENTRYPOINT ["/usr/local/bin/run.sh"]

# 为 ENTRYPOINT 提供默认参数
# 在这个案例中，我们不提供默认参数，让用户在 docker run 时手动传入测试用例数量
CMD []
